---
name: _benchmark

env:
  PYPERFORMANCE_HASH: 2e053ce183aca6f5dce64b071c90dd59ebadb065
  PYSTON_BENCHMARKS_HASH: d4868ff7825f3996e0005197643ed56eba4fb567

on:
  workflow_call:
    inputs:
      fork:
        description: Fork of cinder to benchmark
        type: string
      ref:
        description: Branch, tag or (full) SHA commit to benchmark
        type: string
      machine:
        description: Machine to run on
        type: string
      benchmarks:
        description: Benchmarks to run (comma-separated; empty runs all benchmarks)
        type: string
      pgo:
        description: Build with PGO
        type: boolean
      dry_run:
        description: 'Dry run: Do not commit to the repo'
        type: boolean
      force:
        description: Rerun and replace results if commit already exists
        type: boolean
      perf:
        description: Collect Linux perf profiling data (Linux only)
        type: boolean

  workflow_dispatch:
    inputs:
      fork:
        description: Fork of cinder to benchmark
        type: string
        default: facebookincubator
      ref:
        description: Branch, tag or (full) SHA commit to benchmark
        type: string
        default: main
      machine:
        description: Machine to run on
        default: linux-amd64
        type: choice
        options:
        - linux-x64-ec2runner
        - all
      benchmarks:
        description: Benchmarks to run (comma-separated; empty runs all benchmarks)
        type: string
      pgo:
        description: Build with PGO
        type: boolean
      dry_run:
        description: 'Dry run: Do not commit to the repo'
        type: boolean
      force:
        description: Rerun and replace results if commit already exists
        type: boolean
      perf:
        description: Collect Linux perf profiling data (Linux only)
        type: boolean

jobs:
  benchmark-linux-x64-ec2runner:
    runs-on: [self-hosted, Linux, bare-metal, linux-x64-ec2runner]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.fork }}/cinder
        path: cpython
        ref: ${{ inputs.ref }}
        fetch-depth: 50
    - name: Install dependencies
      run: |
        python -m venv venv
        venv/bin/python -m pip install -r requirements.txt
    - name: Should we run?
      if: ${{ always() }}
      id: should_run
      run: |
        venv/bin/python -m bench_runner.scripts.should_run ${{ inputs.force }} ${{ inputs.fork }} ${{ inputs.ref }} ${{ inputs.machine }} >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      with:
        repository: pyston/python-macrobenchmarks
        path: pyston-benchmarks
        ref: ${{ env.PYSTON_BENCHMARKS_HASH }}
    - uses: actions/checkout@v3
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      with:
        repository: python/pyperformance
        path: pyperformance
        ref: ${{ env.PYPERFORMANCE_HASH }}
    - name: Build Python
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      run: |
        cd cinder
        export OPT=-O2
        ./configure --with-pydebug
        make -j
    - name: Install pyperformance
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      run: |
        venv/bin/python -m pip install --no-binary :all: ./pyperformance
    - name: Tune system
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      run: |
        sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH venv/bin/python -m pyperf system tune
    - name: Tune for perf
      if: ${{ steps.should_run.outputs.should_run != 'false' && inputs.perf }}
      run: |
        sudo bash -c "echo 100000 > /proc/sys/kernel/perf_event_max_sample_rate"
    - name: Running pyperformance
      if: ${{ steps.should_run.outputs.should_run != 'false' }}
      run: |
        rm -rf ~/.debug/*
        venv/bin/python -m bench_runner.scripts.run_benchmarks benchmark cinder/python ${{ inputs.fork }} ${{ inputs.ref }} ${{ inputs.benchmarks || 'all' }} ${{ inputs.perf }} --run_id ${{ github.run_id }}
    - name: Upload benchmark artifacts
      if: ${{ steps.should_run.outputs.should_run != 'false' && !inputs.perf }}
      uses: actions/upload-artifact@v3
      with:
        name: benchmark
        path: |
          benchmark.json
    - name: Upload perf artifacts
      if: ${{ steps.should_run.outputs.should_run != 'false' && inputs.perf }}
      uses: actions/upload-artifact@v3
      with:
        name: perf
        path: |
          profiling/results
      # Pull again, since another job may have committed results in the meantime
    - name: pull
      if: ${{ steps.should_run.outputs.should_run != 'false' && !inputs.dry_run &&
        !inputs.perf }}
      run: |
        # Another benchmarking task may have created results for the same
        # commit while the above was running. This "magic" incantation means
        # that any local results for this commit will override anything we
        # just pulled in in that case.
        git pull -s recursive -X ours --autostash --rebase
    - name: Add to repo
      if: ${{ steps.should_run.outputs.should_run != 'false' && !inputs.dry_run &&
        !inputs.perf }}
      uses: EndBug/add-and-commit@v9
      with:
        add: results

    if: ${{ (inputs.machine == 'linux-x64-ec2runner' || inputs.machine ==
      'all') }}
