---
name: _generate

"on":
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      force:
        description: "Regenerate all of the derived data, even if it already exists"
        type: boolean
        default: false
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  generate-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: install dependencies
        run:
          python -m pip install -r requirements.txt
      - name: regenerate
        run:
          python -m bench_runner.scripts.generate_results ${{ inputs.force == true && '--force' || '' }}
      - name: List generated files
        run: |
          # List files in the working directory
          ls -R
      - name: Add to repo
        uses: EndBug/add-and-commit@v9
        if: ${{ !inputs.dry_run }}
        with:
          add: "['results', 'README.md', 'RESULTS.md', 'longitudinal.png', 'profiling/profiling.png', 'profiling/profiling.md']"
          message: Benchmarking results for @${{ github.actor }}
