---
name: _publish

"on":
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      force:
        description: "Regenerate all of the derived data, even if it already exists"
        type: boolean
        default: false
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: private
          ref: main
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          path: public
          ref: main
          repository: faster-cpython/benchmarking-public
          token: ${{ secrets.BENCHMARK_MIRROR }}
      - name: Mirror
        run: |
          cd public
          git remote add upstream $PWD/../private
          git fetch upstream
          git reset --hard upstream/main
      - name: Push
        if: ${{ !inputs.dry_run }}
        run: |
          cd public
          git push origin main
